export const AUTH_TYPES = {
  SET_USER: 'SET_USER',
  SET_TOKEN: 'SET_TOKEN',
  LOGOUT: 'LOGOUT'
};

export const USER_TYPES = {
  SET_USERS: 'SET_USERS',
  SET_USER_DETAIL: 'SET_USER_DETAIL',
  ADD_USER: 'ADD_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER'
};

export const PERMISSION_TYPES = {
  SET_ROLES: 'SET_ROLES',
  SET_PERMISSIONS: 'SET_PERMISSIONS',
  SET_USER_ROLES: 'SET_USER_ROLES',
  SET_USER_DIRECT_PERMISSIONS: 'SET_USER_DIRECT_PERMISSIONS',
  SET_INHERITED_PERMISSIONS: 'SET_INHERITED_PERMISSIONS',
  SET_USER_ATTRIBUTES: 'SET_USER_ATTRIBUTES',
  SET_POLICIES: 'SET_POLICIES'
};

export const ATTRIBUTE_TYPES = {
  SET_ATTRIBUTES: 'SET_ATTRIBUTES',
  SET_USER_ATTRIBUTES: 'SET_USER_ATTRIBUTES'
};